const tracks = [
  {
    title: "Fall in Love Alone",
    artist: "Stacey Ryan",
    src: "assets/lagu1.mp3",
    cover: "assets/cover1.jpg",
    videoCover: "assets/video1.mp4",
  },
  {
    title: "One The Way",
    artist: "AiNa The End",
    src: "assets/lagu2.mp3",
    cover: "assets/cover2.jpg",
    videoCover: "assets/video2.mp4",
  },
  {
    title: "Best Friends",
    artist: "Rex Orange",
    src: "assets/lagu3.mp3",
    cover: "assets/cover3.jpg",
  },
  {
    title: "Line Without hook",
    artist: "Rick Montogeomery",
    src: "assets/lagu4.mp3",
    cover: "assets/cover4.jpg",
    videoCover: "assets/video4.mp4",
  },
  {
    title: "Every summertime",
    artist: "NIKI",
    src: "assets/lagu5.mp3",
    cover: "assets/cover5.jpg",
    videoCover: "assets/video5.mp4",
  },
  {
    title: "Blue",
    artist: "Yung Kai",
    src: "assets/lagu6.mp3",
    cover: "assets/cover6.jpg",
    videoCover: "assets/video6.mp4",
  },
  {
    title: "Double Take",
    artist: "Druv",
    src: "assets/lagu7.mp3",
    cover: "assets/cover7.jpg",
    videoCover: "assets/video7.mp4",
  },
  {
    title: "Dandelions",
    artist: "Ruth B.",
    src: "assets/lagu8.mp3",
    cover: "assets/cover8.jpg",
    videoCover: "assets/video8.mp4",
  },
  {
    title: "Two Birds",
    artist: "Regina Spektor",
    src: "assets/lagu9.mp3",
    cover: "assets/cover9.jpg",
  },
  {
    title: "Devil Disguise",
    artist: "Marino",
    src: "assets/lagu10.mp3",
    cover: "assets/cover10.jpg",
    videoCover: "assets/video10.mp4",
  },
  {
    title: "Cuma Teman",
    artist: "Ryo",
    src: "assets/lagu12.mp3",
    cover: "assets/Ryo.jpeg",
    videoCover: "assets/video11.mp4",
  },
  {
    title: "December",
    artist: "Neck Deep",
    src: "assets/lagu11.mp3",
    cover: "assets/cover11.jpg",
    videoCover: "assets/video12.mp4",
  },
  {
    title: "Masa Lalu",
    artist: "Chaeroel",
    src: "assets/lagu13.mp3",
    cover: "assets/cover13.jpeg",
    videoCover: "assets/video13.mp4",
  },
  {
    title: "Always",
    artist: "Daniel Chaesar",
    src: "assets/lagu14.mp3",
    cover: "assets/cover14.jpeg",
    videoCover: "assets/video14.mp4",
  },
  {
    title: "Glue",
    artist: "Beabadoobee",
    src: "assets/lagu15.mp3",
    cover: "assets/cover15.jpeg",
  },
  {
    title: "Lowkey",
    artist: "NIKI",
    src: "assets/lagu16.mp3",
    cover: "assets/cover16.jpeg",
  },
  {
    title: "Wilflower",
    artist: "Billie Elish",
    src: "assets/lagu17.mp3",
    cover: "assets/cover17.jpeg",
  },
  {
    title: "Shade",
    artist: "Rex Orange",
    src: "assets/lagu18.mp3",
    cover: "assets/cover18.jpeg",
  },
  {
    title: "aBoUt u",
    artist: "RYO",
    src: "assets/lagu19.mp3",
    cover: "assets/cover19.jpeg",
    videoCover: "assets/video19.mp4",
  },
];
