/* data.js - Database Lagu Portfolio */

const tracks = [
  {
    title: "Fall in Love Alone",
    emoji: "🎢",
    color: "#ff6b81",
    artist: "Stacey Ryan",
    src: "assets/lagu1.mp3",
    cover: "assets/cover1.jpg",
    videoCover: "assets/video1.mp4",
  },
  {
    title: "On The Way",
    emoji: "🏍️",
    color: "#e17055",
    artist: "AiNa The End",
    src: "assets/lagu2.mp3",
    cover: "assets/cover2.jpg",
    videoCover: "assets/video2.mp4",
  },
  {
    title: "Best Friends",
    emoji: "🌻",
    color: "#f1c40f",
    artist: "Rex Orange County",
    src: "assets/lagu3.mp3",
    cover: "assets/cover3.jpg",
  },
  {
    title: "Line Without a Hook",
    emoji: "🎣",
    color: "#00cec9",
    artist: "Rick Montgomery",
    src: "assets/lagu4.mp3",
    cover: "assets/cover4.jpg",
    videoCover: "assets/video4.mp4",
  },
  {
    title: "Every Summertime",
    emoji: "🌇",
    color: "#fab1a0",
    artist: "NIKI",
    src: "assets/lagu5.mp3",
    cover: "assets/cover5.jpg",
    videoCover: "assets/video5.mp4",
  },
  {
    title: "Blue",
    emoji: "🐳",
    color: "#0984e3",
    artist: "Yung Kai",
    src: "assets/lagu6.mp3",
    cover: "assets/cover6.jpg",
    videoCover: "assets/video6.mp4",
  },
  {
    title: "Double Take",
    emoji: "📸",
    color: "#a29bfe",
    artist: "Dhruv",
    src: "assets/lagu7.mp3",
    cover: "assets/cover7.jpg",
    videoCover: "assets/video7.mp4",
  },
  {
    title: "Dandelions",
    emoji: "🌼",
    color: "#fdcb6e",
    artist: "Ruth B.",
    src: "assets/lagu8.mp3",
    cover: "assets/cover8.jpg",
    videoCover: "assets/video8.mp4",
  },
  {
    title: "Two Birds",
    emoji: "🕊️",
    color: "#b2bec3",
    artist: "Regina Spektor",
    src: "assets/lagu9.mp3",
    cover: "assets/cover9.jpg",
  },
  {
    title: "Devil Disguise",
    emoji: "😈",
    color: "#8854d0",
    artist: "Marino",
    src: "assets/lagu10.mp3",
    cover: "assets/cover10.jpg",
    videoCover: "assets/video10.mp4",
  },
  {
    title: "Cuma Teman",
    emoji: "🤡",
    color: "#636e72",
    artist: "Ryo",
    src: "assets/lagu12.mp3",
    cover: "assets/Ryo.jpeg",
    videoCover: "assets/video11.mp4",
  },
  {
    title: "December",
    emoji: "🧣",
    color: "#74b9ff",
    artist: "Neck Deep",
    src: "assets/lagu11.mp3",
    cover: "assets/cover11.jpg",
    videoCover: "assets/video12.mp4",
  },
  {
    title: "Masa Lalu",
    emoji: "📻",
    color: "#d35400",
    artist: "Chaeroel",
    src: "assets/lagu13.mp3",
    cover: "assets/cover13.jpeg",
    videoCover: "assets/video13.mp4",
  },
  {
    title: "Always",
    emoji: "🌙",
    color: "#2c3e50",
    artist: "Daniel Caesar",
    src: "assets/lagu14.mp3",
    cover: "assets/cover14.jpeg",
    videoCover: "assets/video14.mp4",
  },
  {
    title: "Glue Song",
    emoji: "🍯",
    color: "#fd79a8",
    artist: "Beabadoobee",
    src: "assets/lagu15.mp3",
    cover: "assets/cover15.jpeg",
  },
  {
    title: "Lowkey",
    emoji: "🤫",
    color: "#2d3436",
    artist: "NIKI",
    src: "assets/lagu16.mp3",
    cover: "assets/cover16.jpeg",
  },
  {
    title: "Wildflower",
    emoji: "🌾",
    color: "#badc58",
    artist: "Billie Eilish",
    src: "assets/lagu17.mp3",
    cover: "assets/cover17.jpeg",
  },
  {
    title: "Shade",
    emoji: "🌴",
    color: "#1abc9c",
    artist: "Rex Orange County",
    src: "assets/lagu18.mp3",
    cover: "assets/cover18.jpeg",
  },
  {
    title: "About You",
    emoji: "🌫️",
    color: "#e84393",
    artist: "RYO",
    src: "assets/lagu19.mp3",
    cover: "assets/cover19.jpeg",
    videoCover: "assets/video19.mp4",
  },
  {
    title: "Ngga Dulu",
    emoji: "✋",
    color: "#781eee",
    artist: "Chalay",
    src: "assets/NgaaDulu20.mp3",
    cover: "assets/NgaaDulu20.jpg",
    videoCover: "assets/NgaaDulu20.mp4",
  },
  {
    title: "Her",
    emoji: "👸",
    color: "#ffa502",
    artist: "JVKE",
    src: "assets/Her21.mp3",
    cover: "assets/Her21.jpg",
    videoCover: "assets/Her21.mp4",
  },
  {
    title: "Garam & Madu",
    emoji: "🥨",
    color: "#e67e22",
    artist: "Tenxi, Naykilla",
    src: "assets/Garam22.mp3",
    cover: "assets/Garam22.jpg",
    videoCover: "assets/Garam22.mp4",
  },
  {
    title: "Minggu",
    emoji: "🌃",
    color: "#6c5ce7",
    artist: "White Chorus",
    src: "assets/Minggu23.mp3",
    cover: "assets/Minggu23.jpeg",
    videoCover: "assets/Minggu23.mp4",
  },
  {
    title: "Love Me Not",
    emoji: "🥀",
    color: "#be2edd",
    artist: "Ravyn Lenae",
    src: "assets/Lovemenot24.mp3",
    cover: "assets/Lovemenot24.jpeg",
    videoCover: "assets/Lovemenot24.mp4",
  },
  {
    title: "FRIENDZONE",
    emoji: "🚧",
    color: "#535c68",
    artist: "XBOY, Faya",
    src: "assets/FRIENDZONE25.mp3",
    cover: "assets/FRIENDZONE25.jpg",
  },
];
